### ISSUE TITLE
Labs ideas

### ISSUE THREAD

**Issue by alexgavrisco** [Alexx-G/PR-labs#1]
- [x] [L1] TCP - Client - Server app
- [ ] [L2] UDP - Client-Server app (minimal DNS service)
  - [ ] UDP based chat with discovery service (discover available people - multicast/broadcast, send/receive messages - unicast)
  - [ ] UDP based app for team collaboration (shared whiteboard etc)
- [ ] [L3] Reverse engineering of a communication protocol (at application lvl) [TODO: implement/find an app]  (Objective - use tools to capture data from an app and examine it)
- [ ] [L4} Network Sniffer or implement SMTP/IMAP clients (Objective - capture raw ip packets and parse according to protocol specs) (alternative objective - use existing services/protocols to implement client apps)
- [ ] [L5] HTTP Crawler (using only sockets, no HTTP client library)
- [ ] [L6] HTTP server (multiple clients, routing) (NO frameworks/routing libraries etc)

**Comment by alexgavrisco** [comment]
Also, it might make sense to merge L5 and L6 into a single lab for HTTP client and server apps.
And add a lab related to network attacks:
  - https://en.wikipedia.org/wiki/Slowloris_(computer_security)
  - https://www.haproxy.com/blog/what-is-a-slow-post-attack-and-how-turn-haproxy-into-your-first-line-of-defense/

Or something related to brokers:
  - Implement a simple system which displays "real-time" updates from multiple clients data using RabbitMQ/Kafka/etc

**Comment by alexgavrisco** [comment]
Leaving this as source of ideas for alternative scenarios.
